services:
  - type: worker
    name: icealpha-hunter
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8558570286:AAF5-FOPUplRxzeCAc_zbJEQWbNMKYogkKQ
      - key: HELIUS_API_KEY
        value: 8215b2fb-5544-4c82-8806-5721900bfa35
      # ... add all other vars

